# -*- coding: utf-8 -*-
"""
Digital Turnover Tab - Complete Dossier Management
===================================================
Build traceable line dossiers from engineering, weld, documents,
test and handover records with full CRUD, search, export and
detail view capabilities.
"""
from __future__ import annotations

import os
import csv
import datetime
import logging
from pathlib import Path

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QGridLayout,
    QLabel, QComboBox, QLineEdit, QPushButton,
    QTableWidget, QTableWidgetItem, QHeaderView,
    QMessageBox, QFrame, QProgressBar, QDialog,
    QTextEdit, QFileDialog, QMenu, QSplitter,
    QGroupBox, QAbstractItemView, QStyledItemDelegate,
    QApplication, QTabWidget,
)
from PyQt6.QtCore import (
    Qt, QTimer, QThread, pyqtSignal,
)
from PyQt6.QtGui import (
    QColor, QFont, QPainter, QBrush, QPen, QAction, QCursor,
)

from db.models import Project, LineListItem, TurnoverDossier
from services.turnover_dossier_service import TurnoverDossierService

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────
#  STATUS COLOR MAP
# ─────────────────────────────────────────────
STATUS_COLORS = {
    "Complete":   {"bg": "#e6f9ed", "fg": "#0d7a3e", "border": "#27ae60"},
    "Partial":    {"bg": "#fff8e6", "fg": "#b8860b", "border": "#f39c12"},
    "Draft":      {"bg": "#e8f0fe", "fg": "#1a56db", "border": "#3b82f6"},
    "Failed":     {"bg": "#fde8e8", "fg": "#c0392b", "border": "#e74c3c"},
    "In Review":  {"bg": "#f0e6ff", "fg": "#6c3483", "border": "#8e44ad"},
    "Approved":   {"bg": "#e6f9ed", "fg": "#0d7a3e", "border": "#27ae60"},
    "Rejected":   {"bg": "#fde8e8", "fg": "#c0392b", "border": "#e74c3c"},
}

TABLE_COLUMNS = [
    "ID", "Dossier Number", "Scope / Line", "Status",
    "Completeness", "Generated At", "Generated By", "File Path", "Notes",
]

MAX_DISPLAY_ROWS = 500

MAIN_STYLESHEET = """
    QWidget#digitalTurnoverTab {
        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                                    stop:0 #f8fafc, stop:1 #eef2f7);
    }
    QFrame#headerCard {
        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                                    stop:0 #102a43, stop:1 #1a365d);
        border-radius: 16px; padding: 20px;
    }
    QFrame#filterCard, QFrame#statsCard, QFrame#actionsCard {
        background: white; border: 1px solid #e2e8f0;
        border-radius: 12px; padding: 16px;
    }
    QFrame#filterCard:hover, QFrame#statsCard:hover, QFrame#actionsCard:hover {
        border-color: #3b82f6;
    }
    QLabel#mainTitle {
        color: white; font-size: 26px; font-weight: 800;
        font-family: 'Segoe UI', 'Vazirmatn', sans-serif;
    }
    QLabel#mainSubtitle {
        color: #94a3b8; font-size: 13px; font-weight: 400;
    }
    QLabel#sectionTitle {
        color: #1e293b; font-size: 15px; font-weight: 700;
    }
    QLabel#statValue { font-size: 28px; font-weight: 800; color: #1e293b; }
    QLabel#statLabel { font-size: 11px; color: #64748b; font-weight: 500; }
    QLineEdit {
        padding: 10px 14px; border: 2px solid #e2e8f0;
        border-radius: 8px; font-size: 13px;
        background: white; color: #1e293b;
        selection-background-color: #3b82f6;
    }
    QLineEdit:focus { border-color: #3b82f6; background: #f8faff; }
    QLineEdit:hover { border-color: #94a3b8; }
    QComboBox {
        padding: 10px 14px; border: 2px solid #e2e8f0;
        border-radius: 8px; font-size: 13px;
        background: white; color: #1e293b; min-width: 180px;
    }
    QComboBox:focus, QComboBox:hover { border-color: #3b82f6; }
    QComboBox::drop-down { border: none; width: 30px; }
    QComboBox::down-arrow {
        image: none;
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 6px solid #64748b; margin-right: 10px;
    }
    QComboBox QAbstractItemView {
        border: 2px solid #e2e8f0; border-radius: 8px;
        background: white;
        selection-background-color: #eff6ff;
        selection-color: #1e293b; padding: 4px;
    }
    QPushButton#primaryBtn {
        background: qlineargradient(x1:0,y1:0,x2:1,y2:0,
            stop:0 #3b82f6, stop:1 #2563eb);
        color: white; border: none; padding: 11px 24px;
        border-radius: 8px; font-size: 13px; font-weight: 700;
        min-width: 140px;
    }
    QPushButton#primaryBtn:hover {
        background: qlineargradient(x1:0,y1:0,x2:1,y2:0,
            stop:0 #2563eb, stop:1 #1d4ed8);
    }
    QPushButton#primaryBtn:pressed { background: #1e40af; }
    QPushButton#successBtn {
        background: qlineargradient(x1:0,y1:0,x2:1,y2:0,
            stop:0 #10b981, stop:1 #059669);
        color: white; border: none; padding: 11px 24px;
        border-radius: 8px; font-size: 13px; font-weight: 700;
        min-width: 140px;
    }
    QPushButton#successBtn:hover {
        background: qlineargradient(x1:0,y1:0,x2:1,y2:0,
            stop:0 #059669, stop:1 #047857);
    }
    QPushButton#dangerBtn {
        background: qlineargradient(x1:0,y1:0,x2:1,y2:0,
            stop:0 #ef4444, stop:1 #dc2626);
        color: white; border: none; padding: 11px 24px;
        border-radius: 8px; font-size: 13px; font-weight: 700;
        min-width: 100px;
    }
    QPushButton#dangerBtn:hover {
        background: qlineargradient(x1:0,y1:0,x2:1,y2:0,
            stop:0 #dc2626, stop:1 #b91c1c);
    }
    QPushButton#secondaryBtn {
        background: white; color: #374151;
        border: 2px solid #d1d5db;
        padding: 10px 20px; border-radius: 8px;
        font-size: 13px; font-weight: 600;
    }
    QPushButton#secondaryBtn:hover {
        background: #f9fafb; border-color: #3b82f6; color: #3b82f6;
    }
    QTableWidget {
        background: white; border: 1px solid #e2e8f0;
        border-radius: 12px; gridline-color: #f1f5f9;
        font-size: 12px;
        selection-background-color: #eff6ff;
        selection-color: #1e293b;
        alternate-background-color: #f8fafc;
    }
    QTableWidget::item { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; }
    QTableWidget::item:selected { background: #dbeafe; color: #1e293b; }
    QTableWidget::item:hover { background: #f0f7ff; }
    QHeaderView::section {
        background: qlineargradient(x1:0,y1:0,x2:0,y2:1,
            stop:0 #f8fafc, stop:1 #eef2f7);
        color: #475569; font-weight: 700; font-size: 12px;
        padding: 10px 12px; border: none;
        border-bottom: 2px solid #e2e8f0;
        border-right: 1px solid #e2e8f0;
    }
    QHeaderView::section:hover { background: #e2e8f0; color: #1e293b; }
    QProgressBar {
        border: none; border-radius: 6px;
        background: #e2e8f0; height: 12px;
        text-align: center; font-size: 10px;
        font-weight: 700; color: white;
    }
    QProgressBar::chunk {
        border-radius: 6px;
        background: qlineargradient(x1:0,y1:0,x2:1,y2:0,
            stop:0 #3b82f6, stop:1 #10b981);
    }
    QGroupBox {
        font-size: 13px; font-weight: 700; color: #374151;
        border: 2px solid #e5e7eb; border-radius: 10px;
        margin-top: 14px; padding: 14px; padding-top: 28px;
    }
    QGroupBox::title {
        subcontrol-origin: margin; subcontrol-position: top left;
        left: 14px; padding: 2px 8px;
        background: white; border-radius: 4px;
    }
    QScrollBar:vertical { background: #f1f5f9; width: 10px; border-radius: 5px; }
    QScrollBar::handle:vertical { background: #94a3b8; border-radius: 5px; min-height: 30px; }
    QScrollBar::handle:vertical:hover { background: #64748b; }
    QScrollBar:horizontal { background: #f1f5f9; height: 10px; border-radius: 5px; }
    QScrollBar::handle:horizontal { background: #94a3b8; border-radius: 5px; min-width: 30px; }
"""


# ─────────────────────────────────────────────
#  BACKGROUND WORKER
# ─────────────────────────────────────────────
class DossierGeneratorThread(QThread):
    """Background worker for dossier generation — UI stays responsive."""
    finished = pyqtSignal(dict)
    error = pyqtSignal(str)
    progress = pyqtSignal(int, str)

    def __init__(self, service, project_id, line_number, username):
        super().__init__()
        self.service = service
        self.project_id = project_id
        self.line_number = line_number
        self.username = username

    def run(self):
        try:
            self.progress.emit(10, "Initializing dossier generation...")
            self.progress.emit(30, "Collecting engineering data...")
            self.progress.emit(50, "Processing weld records...")
            self.progress.emit(70, "Compiling documents...")

            result = self.service.generate_line_dossier(
                self.project_id,
                self.line_number,
                self.username,
            )

            self.progress.emit(90, "Finalizing dossier...")
            self.progress.emit(100, "Complete!")
            self.finished.emit(result)

        except Exception as e:
            logger.exception("Dossier generation failed.")
            self.error.emit(str(e))


# ─────────────────────────────────────────────
#  DETAIL DIALOG
# ─────────────────────────────────────────────
class DossierDetailDialog(QDialog):
    """Detailed view of a single dossier."""

    def __init__(self, dossier_data: dict, parent=None):
        super().__init__(parent)
        self.dossier_data = dossier_data
        self.setWindowTitle(
            f"📋 Dossier Details — {dossier_data.get('dossier_number', 'N/A')}"
        )
        self.setMinimumSize(700, 550)
        self.setStyleSheet(MAIN_STYLESHEET)
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)
        layout.setSpacing(16)
        layout.setContentsMargins(20, 20, 20, 20)

        title_label = QLabel(
            f"📋 {self.dossier_data.get('dossier_number', 'N/A')}"
        )
        title_label.setStyleSheet(
            "font-size: 22px; font-weight: 800; color: #102a43;"
        )
        layout.addWidget(title_label)

        tabs = QTabWidget()
        tabs.setStyleSheet("""
            QTabWidget::pane {
                border: 1px solid #e2e8f0; border-radius: 8px;
                background: white; padding: 12px;
            }
            QTabBar::tab {
                padding: 10px 20px; font-weight: 600; font-size: 12px;
                border: none; border-bottom: 3px solid transparent;
                color: #64748b;
            }
            QTabBar::tab:selected {
                color: #3b82f6; border-bottom-color: #3b82f6;
            }
            QTabBar::tab:hover { color: #1e293b; }
        """)

        tabs.addTab(self._create_general_tab(), "📄 General Info")
        tabs.addTab(self._create_contents_tab(), "📑 Contents")
        tabs.addTab(self._create_history_tab(), "🕐 History")
        layout.addWidget(tabs)

        btn_layout = QHBoxLayout()
        btn_layout.addStretch()

        export_btn = QPushButton("📥 Export PDF")
        export_btn.setObjectName("primaryBtn")
        export_btn.clicked.connect(self._export_pdf)
        btn_layout.addWidget(export_btn)

        close_btn = QPushButton("Close")
        close_btn.setObjectName("secondaryBtn")
        close_btn.clicked.connect(self.close)
        btn_layout.addWidget(close_btn)
        layout.addLayout(btn_layout)

    def _create_general_tab(self) -> QWidget:
        widget = QWidget()
        layout = QGridLayout(widget)
        layout.setSpacing(12)

        fields = [
            ("Dossier Number:", self.dossier_data.get("dossier_number", "N/A")),
            ("Scope / Line:", self.dossier_data.get("scope_key", "N/A")),
            ("Status:", self.dossier_data.get("status", "N/A")),
            ("Completeness:", f"{self.dossier_data.get('completeness_pct', 0):.0f}%"),
            ("Generated At:", str(self.dossier_data.get("generated_at", "N/A"))),
            ("Generated By:", self.dossier_data.get("generated_by", "N/A")),
            ("File Path:", self.dossier_data.get("generated_path", "N/A")),
        ]

        for row, (label_text, value_text) in enumerate(fields):
            label = QLabel(label_text)
            label.setStyleSheet("font-weight: 700; color: #374151; font-size: 13px;")

            value = QLabel(str(value_text))
            value.setStyleSheet("color: #1e293b; font-size: 13px;")
            value.setTextInteractionFlags(
                Qt.TextInteractionFlag.TextSelectableByMouse
            )
            layout.addWidget(label, row, 0)
            layout.addWidget(value, row, 1)

        progress = QProgressBar()
        progress.setValue(int(self.dossier_data.get("completeness_pct", 0)))
        progress.setMinimumHeight(20)
        layout.addWidget(QLabel("Completeness:"), len(fields), 0)
        layout.addWidget(progress, len(fields), 1)
        layout.setRowStretch(len(fields) + 1, 1)
        return widget

    def _create_contents_tab(self) -> QWidget:
        widget = QWidget()
        layout = QVBoxLayout(widget)

        text_edit = QTextEdit()
        text_edit.setReadOnly(True)
        text_edit.setStyleSheet(
            "font-family: 'Consolas', 'Courier New', monospace; font-size: 12px;"
        )

        contents = self.dossier_data.get("contents", {})
        if isinstance(contents, dict):
            html = "<h3>📑 Dossier Contents</h3><hr>"
            for section, items in contents.items():
                html += f"<h4>▸ {section}</h4>"
                if isinstance(items, list):
                    for item in items:
                        html += f"<p style='margin-left:20px;'>• {item}</p>"
                else:
                    html += f"<p style='margin-left:20px;'>{items}</p>"
            text_edit.setHtml(html)
        else:
            text_edit.setPlainText(
                str(contents) if contents else "No contents available."
            )

        layout.addWidget(text_edit)
        return widget

    def _create_history_tab(self) -> QWidget:
        widget = QWidget()
        layout = QVBoxLayout(widget)

        history_table = QTableWidget(0, 4)
        history_table.setHorizontalHeaderLabels([
            "Date/Time", "Action", "User", "Details"
        ])
        history_table.horizontalHeader().setSectionResizeMode(
            QHeaderView.ResizeMode.Stretch
        )
        history_table.setAlternatingRowColors(True)

        history_table.insertRow(0)
        history_table.setItem(
            0, 0,
            QTableWidgetItem(str(self.dossier_data.get("generated_at", "")))
        )
        history_table.setItem(0, 1, QTableWidgetItem("Generated"))
        history_table.setItem(
            0, 2,
            QTableWidgetItem(self.dossier_data.get("generated_by", ""))
        )
        history_table.setItem(
            0, 3,
            QTableWidgetItem(
                f"Completeness: "
                f"{self.dossier_data.get('completeness_pct', 0):.0f}%"
            )
        )
        layout.addWidget(history_table)
        return widget

    def _export_pdf(self):
        file_path, _ = QFileDialog.getSaveFileName(
            self,
            "Export Dossier as PDF",
            f"{self.dossier_data.get('dossier_number', 'dossier')}.pdf",
            "PDF Files (*.pdf)"
        )
        if file_path:
            QMessageBox.information(
                self, "Export",
                f"PDF export to:\n{file_path}\n\n(Implement PDF generation here)"
            )


# ─────────────────────────────────────────────
#  STAT CARD
# ─────────────────────────────────────────────
class StatCard(QFrame):
    """KPI stat card with icon and value."""

    def __init__(self, icon: str, label: str, value: str = "0",
                 color: str = "#3b82f6"):
        super().__init__()
        self.setObjectName("statsCard")
        self.setFixedHeight(95)
        self.setMinimumWidth(150)

        layout = QVBoxLayout(self)
        layout.setSpacing(4)
        layout.setContentsMargins(16, 12, 16, 12)

        top_layout = QHBoxLayout()
        icon_label = QLabel(icon)
        icon_label.setStyleSheet(f"font-size: 24px; color: {color};")
        top_layout.addWidget(icon_label)
        top_layout.addStretch()

        self.value_label = QLabel(str(value))
        self.value_label.setObjectName("statValue")
        self.value_label.setStyleSheet(
            f"font-size: 28px; font-weight: 800; color: {color};"
        )
        top_layout.addWidget(self.value_label)
        layout.addLayout(top_layout)

        text_label = QLabel(label)
        text_label.setObjectName("statLabel")
        text_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(text_label)

    def set_value(self, value):
        self.value_label.setText(str(value))


# ─────────────────────────────────────────────
#  PROGRESS BAR DELEGATE
# ─────────────────────────────────────────────
class ProgressBarDelegate(QStyledItemDelegate):
    """Renders an inline progress bar in the Completeness column."""

    def paint(self, painter, option, index):
        text = index.data(Qt.ItemDataRole.DisplayRole)
        if text is None:
            super().paint(painter, option, index)
            return

        try:
            value = int(str(text).replace("%", "").strip())
        except (ValueError, AttributeError):
            super().paint(painter, option, index)
            return

        painter.save()
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)

        rect = option.rect.adjusted(8, 6, -8, -6)

        if value >= 90:
            bar_color = QColor("#10b981")
            bg_color = QColor("#d1fae5")
        elif value >= 70:
            bar_color = QColor("#3b82f6")
            bg_color = QColor("#dbeafe")
        elif value >= 50:
            bar_color = QColor("#f59e0b")
            bg_color = QColor("#fef3c7")
        else:
            bar_color = QColor("#ef4444")
            bg_color = QColor("#fee2e2")

        painter.setBrush(QBrush(bg_color))
        painter.setPen(Qt.PenStyle.NoPen)
        painter.drawRoundedRect(rect, 4, 4)

        fill_width = int(rect.width() * value / 100)
        fill_rect = rect.adjusted(0, 0, -(rect.width() - fill_width), 0)
        painter.setBrush(QBrush(bar_color))
        painter.drawRoundedRect(fill_rect, 4, 4)

        painter.setPen(QPen(QColor("#1e293b")))
        font = painter.font()
        font.setBold(True)
        font.setPointSize(9)
        painter.setFont(font)
        painter.drawText(rect, Qt.AlignmentFlag.AlignCenter, f"{value}%")

        painter.restore()


# ─────────────────────────────────────────────
#  MAIN TAB
# ─────────────────────────────────────────────
class DigitalTurnoverTab(QWidget):
    """
    Digital Turnover Dossier management tab.
    """
    def __init__(self, db, session):
        super().__init__()
        self.setObjectName("digitalTurnoverTab")
        self.db = db
        self.session = session
        self.svc = TurnoverDossierService(db)
        self._generator_thread: DossierGeneratorThread | None = None
        self._cached_dossiers = []

        self._build_ui()
        self.setStyleSheet(MAIN_STYLESHEET)
        self.refresh()

    # ── UI BUILD ─────────────────────────────────────────────
    def _build_ui(self):
        main_layout = QVBoxLayout(self)
        main_layout.setSpacing(16)
        main_layout.setContentsMargins(20, 20, 20, 20)

        main_layout.addWidget(self._build_header())
        main_layout.addLayout(self._build_stat_cards())
        main_layout.addWidget(self._build_filter_section())
        main_layout.addWidget(self._build_progress_section())
        main_layout.addWidget(self._build_table(), stretch=1)
        main_layout.addWidget(self._build_status_bar())

    def _build_header(self) -> QFrame:
        card = QFrame()
        card.setObjectName("headerCard")

        layout = QVBoxLayout(card)
        layout.setSpacing(6)

        title = QLabel("📦 Digital Turnover  |  Auto Dossier + Traceability")
        title.setObjectName("mainTitle")
        layout.addWidget(title)

        subtitle = QLabel(
            "Build a traceable line dossier from engineering, weld, "
            "documents, test and handover records."
        )
        subtitle.setObjectName("mainSubtitle")
        layout.addWidget(subtitle)
        return card

    def _build_stat_cards(self) -> QHBoxLayout:
        layout = QHBoxLayout()
        layout.setSpacing(12)

        self.stat_total = StatCard("📦", "Total Dossiers", "0", "#3b82f6")
        self.stat_complete = StatCard("✅", "Complete", "0", "#10b981")
        self.stat_partial = StatCard("⏳", "Partial", "0", "#f59e0b")
        self.stat_draft = StatCard("📝", "Draft", "0", "#6366f1")
        self.stat_avg_completeness = StatCard(
            "📊", "Avg Completeness", "0%", "#8b5cf6"
        )

        for c in (self.stat_total, self.stat_complete, self.stat_partial,
                  self.stat_draft, self.stat_avg_completeness):
            layout.addWidget(c)
        return layout

    def _build_filter_section(self) -> QFrame:
        card = QFrame()
        card.setObjectName("filterCard")
        layout = QVBoxLayout(card)
        layout.setSpacing(12)

        section_title = QLabel("🔧 Generate & Filter")
        section_title.setObjectName("sectionTitle")
        layout.addWidget(section_title)

        # Row 1: generation inputs
        row1 = QHBoxLayout()
        row1.setSpacing(10)

        row1.addWidget(QLabel("Project:"))
        self.cmb_project = QComboBox()
        self.cmb_project.setMinimumWidth(250)
        self.cmb_project.currentIndexChanged.connect(self._on_project_changed)
        row1.addWidget(self.cmb_project)

        row1.addWidget(QLabel("Line Number:"))
        self.txt_line = QLineEdit()
        self.txt_line.setPlaceholderText(
            'Enter line number (e.g. 6"-P-001-A1A)'
        )
        self.txt_line.setMinimumWidth(220)
        self.txt_line.returnPressed.connect(self.generate_dossier)
        row1.addWidget(self.txt_line)

        self.btn_generate = QPushButton("⚡ Generate Dossier")
        self.btn_generate.setObjectName("successBtn")
        self.btn_generate.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_generate.clicked.connect(self.generate_dossier)
        row1.addWidget(self.btn_generate)
        layout.addLayout(row1)

        separator = QFrame()
        separator.setFrameShape(QFrame.Shape.HLine)
        separator.setStyleSheet("background: #e2e8f0; max-height: 1px;")
        layout.addWidget(separator)

        # Row 2: filters and actions
        row2 = QHBoxLayout()
        row2.setSpacing(10)

        self.txt_search = QLineEdit()
        self.txt_search.setPlaceholderText(
            "🔍 Search dossier number, scope, path..."
        )
        self.txt_search.setMinimumWidth(280)
        self.txt_search.textChanged.connect(self._apply_filters)
        row2.addWidget(self.txt_search)

        row2.addWidget(QLabel("Status:"))
        self.cmb_status_filter = QComboBox()
        self.cmb_status_filter.addItem("All Statuses", None)
        for status in STATUS_COLORS.keys():
            self.cmb_status_filter.addItem(status, status)
        self.cmb_status_filter.currentIndexChanged.connect(self._apply_filters)
        row2.addWidget(self.cmb_status_filter)

        row2.addWidget(QLabel("Filter Project:"))
        self.cmb_project_filter = QComboBox()
        self.cmb_project_filter.addItem("All Projects", None)
        self.cmb_project_filter.currentIndexChanged.connect(self._apply_filters)
        row2.addWidget(self.cmb_project_filter)

        row2.addStretch()

        self.btn_refresh = QPushButton("↻ Refresh")
        self.btn_refresh.setObjectName("secondaryBtn")
        self.btn_refresh.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_refresh.clicked.connect(self.refresh)
        row2.addWidget(self.btn_refresh)

        self.btn_export = QPushButton("📥 Export CSV")
        self.btn_export.setObjectName("secondaryBtn")
        self.btn_export.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_export.clicked.connect(self.export_csv)
        row2.addWidget(self.btn_export)

        self.btn_delete = QPushButton("🗑 Delete")
        self.btn_delete.setObjectName("dangerBtn")
        self.btn_delete.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_delete.clicked.connect(self.delete_selected)
        row2.addWidget(self.btn_delete)
        layout.addLayout(row2)

        return card

    def _build_progress_section(self) -> QWidget:
        self.progress_widget = QWidget()
        self.progress_widget.setVisible(False)

        layout = QVBoxLayout(self.progress_widget)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(4)

        self.progress_label = QLabel("Generating dossier...")
        self.progress_label.setStyleSheet(
            "font-size: 12px; color: #3b82f6; font-weight: 600;"
        )
        layout.addWidget(self.progress_label)

        self.progress_bar = QProgressBar()
        self.progress_bar.setMinimum(0)
        self.progress_bar.setMaximum(100)
        self.progress_bar.setValue(0)
        self.progress_bar.setMinimumHeight(16)
        layout.addWidget(self.progress_bar)
        return self.progress_widget

    def _build_table(self) -> QTableWidget:
        self.table = QTableWidget(0, len(TABLE_COLUMNS))
        self.table.setHorizontalHeaderLabels(TABLE_COLUMNS)

        self.table.setAlternatingRowColors(True)
        # ✅ FIXED: use QAbstractItemView enums
        self.table.setSelectionBehavior(
            QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.table.setSelectionMode(
            QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.table.setSortingEnabled(True)
        self.table.setEditTriggers(
            QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.table.verticalHeader().setVisible(False)

        header = self.table.horizontalHeader()
        header.setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        header.setStretchLastSection(True)

        column_widths = [50, 180, 160, 100, 120, 150, 100, 200, 150]
        for i, width in enumerate(column_widths):
            if i < len(TABLE_COLUMNS):
                self.table.setColumnWidth(i, width)

        self.table.setColumnHidden(0, True)
        self.table.setItemDelegateForColumn(
            4, ProgressBarDelegate(self.table)
        )

        self.table.doubleClicked.connect(self._on_row_double_clicked)
        self.table.setContextMenuPolicy(
            Qt.ContextMenuPolicy.CustomContextMenu
        )
        self.table.customContextMenuRequested.connect(self._show_context_menu)
        return self.table

    def _build_status_bar(self) -> QFrame:
        bar = QFrame()
        bar.setStyleSheet(
            "background: #f1f5f9; border-radius: 8px; padding: 6px 12px;"
        )

        layout = QHBoxLayout(bar)
        layout.setContentsMargins(12, 6, 12, 6)
        layout.setSpacing(20)

        self.lbl_status_info = QLabel("Ready")
        self.lbl_status_info.setStyleSheet(
            "color: #64748b; font-size: 12px;"
        )
        layout.addWidget(self.lbl_status_info)

        layout.addStretch()

        self.lbl_row_count = QLabel("Rows: 0")
        self.lbl_row_count.setStyleSheet(
            "color: #64748b; font-size: 12px; font-weight: 600;"
        )
        layout.addWidget(self.lbl_row_count)

        self.lbl_selected_count = QLabel("Selected: 0")
        self.lbl_selected_count.setStyleSheet(
            "color: #64748b; font-size: 12px; font-weight: 600;"
        )
        layout.addWidget(self.lbl_selected_count)

        self.table.selectionModel().selectionChanged.connect(
            self._update_selection_count
        )
        return bar

    # ── DATA LOADING ─────────────────────────────────────────
    def refresh(self):
        self._set_status("Loading data...")
        QApplication.processEvents()

        try:
            with self.db.session_scope() as s:
                projects = (
                    s.query(Project)
                    .order_by(Project.project_code)
                    .all()
                )
                self._load_projects(projects)

                dossiers = (
                    s.query(TurnoverDossier)
                    .order_by(TurnoverDossier.id.desc())
                    .limit(MAX_DISPLAY_ROWS)
                    .all()
                )

                self._cached_dossiers = []
                for d in dossiers:
                    self._cached_dossiers.append({
                        "id": d.id,
                        "dossier_number": getattr(d, "dossier_number", ""),
                        "scope_key": getattr(d, "scope_key", ""),
                        "status": getattr(d, "status", ""),
                        "completeness_pct": getattr(d, "completeness_pct", 0) or 0,
                        "generated_at": str(getattr(d, "generated_at", "") or ""),
                        "generated_by": getattr(d, "generated_by", ""),
                        "generated_path": getattr(d, "generated_path", ""),
                        "notes": getattr(d, "notes", ""),
                        "project_id": getattr(d, "project_id", None),
                    })

            self._apply_filters()
            self._update_statistics()
            self._set_status(
                f"Loaded {len(self._cached_dossiers)} dossiers"
            )
        except Exception as e:
            self._set_status(f"Error loading data: {e}")
            QMessageBox.critical(
                self, "Load Error",
                f"Failed to load data:\n{str(e)}"
            )

    def _load_projects(self, projects):
        current_data = self.cmb_project.currentData()
        self.cmb_project.blockSignals(True)
        self.cmb_project.clear()
        for p in projects:
            self.cmb_project.addItem(f"{p.project_code} — {p.title}", p.id)
        if current_data is not None:
            idx = self.cmb_project.findData(current_data)
            self.cmb_project.setCurrentIndex(max(0, idx))
        self.cmb_project.blockSignals(False)

        current_filter = self.cmb_project_filter.currentData()
        self.cmb_project_filter.blockSignals(True)
        self.cmb_project_filter.clear()
        self.cmb_project_filter.addItem("All Projects", None)
        for p in projects:
            self.cmb_project_filter.addItem(
                f"{p.project_code} — {p.title}", p.id
            )
        if current_filter is not None:
            idx = self.cmb_project_filter.findData(current_filter)
            self.cmb_project_filter.setCurrentIndex(max(0, idx))
        self.cmb_project_filter.blockSignals(False)

    def _apply_filters(self):
        search_text = self.txt_search.text().strip().lower()
        status_filter = self.cmb_status_filter.currentData()
        project_filter = self.cmb_project_filter.currentData()

        filtered = []
        for d in self._cached_dossiers:
            if status_filter and d.get("status") != status_filter:
                continue
            if project_filter and d.get("project_id") != project_filter:
                continue
            if search_text:
                searchable = " ".join([
                    str(d.get("dossier_number", "")),
                    str(d.get("scope_key", "")),
                    str(d.get("generated_path", "")),
                    str(d.get("notes", "")),
                    str(d.get("generated_by", "")),
                ]).lower()
                if search_text not in searchable:
                    continue
            filtered.append(d)

        self._populate_table(filtered)

    def _populate_table(self, dossiers: list):
        self.table.setSortingEnabled(False)
        self.table.setRowCount(0)

        for d in dossiers:
            row = self.table.rowCount()
            self.table.insertRow(row)

            values = [
                str(d.get("id", "")),
                d.get("dossier_number", ""),
                d.get("scope_key", ""),
                d.get("status", ""),
                f"{d.get('completeness_pct', 0):.0f}",
                d.get("generated_at", ""),
                d.get("generated_by", ""),
                d.get("generated_path", ""),
                d.get("notes", ""),
            ]

            for col, value in enumerate(values):
                item = QTableWidgetItem(str(value))
                item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

                if col == 3:  # Status column
                    status = str(value)
                    colors = STATUS_COLORS.get(status, {})
                    if colors:
                        item.setBackground(QColor(colors["bg"]))
                        item.setForeground(QColor(colors["fg"]))
                        f = item.font()
                        f.setBold(True)
                        item.setFont(f)

                self.table.setItem(row, col, item)

            self.table.setRowHeight(row, 42)

        self.table.setSortingEnabled(True)
        self.lbl_row_count.setText(f"Rows: {self.table.rowCount()}")
        self._update_selection_count()

    def _update_statistics(self):
        total = len(self._cached_dossiers)
        complete = sum(
            1 for d in self._cached_dossiers if d.get("status") == "Complete"
        )
        partial = sum(
            1 for d in self._cached_dossiers if d.get("status") == "Partial"
        )
        draft = sum(
            1 for d in self._cached_dossiers if d.get("status") == "Draft"
        )

        avg_completeness = 0
        if total > 0:
            avg_completeness = sum(
                d.get("completeness_pct", 0)
                for d in self._cached_dossiers
            ) / total

        self.stat_total.set_value(total)
        self.stat_complete.set_value(complete)
        self.stat_partial.set_value(partial)
        self.stat_draft.set_value(draft)
        self.stat_avg_completeness.set_value(f"{avg_completeness:.0f}%")

    # ── DOSSIER GENERATION ───────────────────────────────────
    def generate_dossier(self):
        project_id = self.cmb_project.currentData()
        line_number = self.txt_line.text().strip()

        if not project_id:
            QMessageBox.warning(
                self, "Validation Error",
                "Please select a project first."
            )
            return

        if not line_number:
            QMessageBox.warning(
                self, "Validation Error",
                "Please enter a line number."
            )
            self.txt_line.setFocus()
            return

        reply = QMessageBox.question(
            self, "Confirm Generation",
            f"Generate dossier for line:\n\n"
            f"  Line: {line_number}\n"
            f"  Project: {self.cmb_project.currentText()}\n\n"
            f"Continue?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.Yes,
        )
        if reply != QMessageBox.StandardButton.Yes:
            return

        # ✅ FIXED: cleanup previous thread
        if self._generator_thread is not None:
            try:
                if self._generator_thread.isRunning():
                    self._generator_thread.wait(2000)
                self._generator_thread.deleteLater()
            except Exception:
                pass
            self._generator_thread = None

        self.btn_generate.setEnabled(False)
        self.btn_generate.setText("⏳ Generating...")
        self.progress_widget.setVisible(True)
        self.progress_bar.setValue(0)

        username = getattr(self.session, "username", "admin")

        self._generator_thread = DossierGeneratorThread(
            self.svc, project_id, line_number, username
        )
        self._generator_thread.progress.connect(self._on_generation_progress)
        self._generator_thread.finished.connect(self._on_generation_finished)
        self._generator_thread.error.connect(self._on_generation_error)
        self._generator_thread.start()

    def _on_generation_progress(self, value: int, message: str):
        self.progress_bar.setValue(value)
        self.progress_label.setText(message)
        self._set_status(message)

    def _on_generation_finished(self, result: dict):
        self.btn_generate.setEnabled(True)
        self.btn_generate.setText("⚡ Generate Dossier")

        QTimer.singleShot(
            1500, lambda: self.progress_widget.setVisible(False)
        )

        self.txt_line.clear()
        self.refresh()

        dossier_num = result.get("dossier_number", "N/A")
        completeness = result.get("completeness_pct", 0)
        path = result.get("path", "N/A")

        QMessageBox.information(
            self, "✅ Dossier Generated Successfully",
            f"Dossier has been generated:\n\n"
            f"  📋 Number: {dossier_num}\n"
            f"  📊 Completeness: {completeness}%\n"
            f"  📁 Path: {path}\n\n"
            f"The dossier is now available in the table."
        )
        self._set_status(f"Dossier {dossier_num} generated successfully")

        if self._generator_thread is not None:
            self._generator_thread.deleteLater()
            self._generator_thread = None

    def _on_generation_error(self, error_message: str):
        self.btn_generate.setEnabled(True)
        self.btn_generate.setText("⚡ Generate Dossier")
        self.progress_widget.setVisible(False)

        QMessageBox.critical(
            self, "❌ Dossier Generation Error",
            f"Failed to generate dossier:\n\n{error_message}\n\n"
            f"Please check the line number and try again."
        )
        self._set_status(f"Generation failed: {error_message}")

        if self._generator_thread is not None:
            self._generator_thread.deleteLater()
            self._generator_thread = None

    # ── DELETE ───────────────────────────────────────────────
    def delete_selected(self):
        selected_rows = self.table.selectionModel().selectedRows()
        if not selected_rows:
            QMessageBox.warning(
                self, "No Selection",
                "Please select one or more dossiers to delete."
            )
            return

        selected_ids = []
        selected_names = []
        for index in selected_rows:
            row = index.row()
            dossier_id = self.table.item(row, 0)
            dossier_name = self.table.item(row, 1)
            if dossier_id:
                selected_ids.append(int(dossier_id.text()))
            if dossier_name:
                selected_names.append(dossier_name.text())

        if not selected_ids:
            return

        names_text = "\n".join(f"  • {name}" for name in selected_names[:10])
        if len(selected_names) > 10:
            names_text += f"\n  ... and {len(selected_names) - 10} more"

        reply = QMessageBox.warning(
            self, "⚠️ Confirm Delete",
            f"Are you sure you want to delete {len(selected_ids)} dossier(s)?\n\n"
            f"{names_text}\n\n"
            f"This action cannot be undone.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No,
        )
        if reply != QMessageBox.StandardButton.Yes:
            return

        try:
            deleted_count = 0
            with self.db.session_scope() as s:
                for dossier_id in selected_ids:
                    # ✅ FIXED: SQLAlchemy 2.0 — use session.get()
                    dossier = s.get(TurnoverDossier, dossier_id)
                    if dossier:
                        s.delete(dossier)
                        deleted_count += 1
                s.commit()

            self.refresh()
            QMessageBox.information(
                self, "✅ Deleted",
                f"Successfully deleted {deleted_count} dossier(s)."
            )
            self._set_status(f"Deleted {deleted_count} dossier(s)")
        except Exception as e:
            logger.exception("Delete failed.")
            QMessageBox.critical(
                self, "Delete Error",
                f"Failed to delete dossiers:\n{str(e)}"
            )

    # ── EXPORT ───────────────────────────────────────────────
    def export_csv(self):
        if self.table.rowCount() == 0:
            QMessageBox.warning(self, "No Data", "There is no data to export.")
            return

        default_name = (
            f"turnover_dossiers_"
            f"{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        )
        file_path, _ = QFileDialog.getSaveFileName(
            self, "Export CSV", default_name,
            "CSV Files (*.csv);;All Files (*)"
        )
        if not file_path:
            return

        try:
            with open(file_path, "w", newline="", encoding="utf-8-sig") as f:
                writer = csv.writer(f)
                headers = [
                    TABLE_COLUMNS[i]
                    for i in range(len(TABLE_COLUMNS)) if i != 0
                ]
                writer.writerow(headers)

                for row in range(self.table.rowCount()):
                    row_data = []
                    for col in range(len(TABLE_COLUMNS)):
                        if col == 0:
                            continue
                        item = self.table.item(row, col)
                        value = item.text() if item else ""
                        if col == 4:
                            value = f"{value}%"
                        row_data.append(value)
                    writer.writerow(row_data)

            QMessageBox.information(
                self, "✅ Export Complete",
                f"Data exported successfully to:\n{file_path}\n\n"
                f"Total rows: {self.table.rowCount()}"
            )
            self._set_status(f"Exported {self.table.rowCount()} rows to CSV")
        except Exception as e:
            logger.exception("CSV export failed.")
            QMessageBox.critical(
                self, "Export Error",
                f"Failed to export CSV:\n{str(e)}"
            )

    # ── EVENT HANDLERS ───────────────────────────────────────
    def _on_project_changed(self, index: int):
        # Placeholder for future cascading behaviour
        pass

    def _on_row_double_clicked(self, index):
        self._show_dossier_details(index.row())

    def _show_dossier_details(self, row: int):
        if row < 0 or row >= self.table.rowCount():
            return

        dossier_data = {}
        column_keys = [
            "id", "dossier_number", "scope_key", "status",
            "completeness_pct", "generated_at", "generated_by",
            "generated_path", "notes",
        ]

        for col, key in enumerate(column_keys):
            item = self.table.item(row, col)
            value = item.text() if item else ""

            if key == "completeness_pct":
                try:
                    value = float(value.replace("%", ""))
                except ValueError:
                    value = 0
            elif key == "id":
                try:
                    value = int(value)
                except ValueError:
                    value = 0

            dossier_data[key] = value

        dialog = DossierDetailDialog(dossier_data, self)
        dialog.exec()

    def _show_context_menu(self, position):
        menu = QMenu(self)
        menu.setStyleSheet("""
            QMenu {
                background: white; border: 1px solid #e2e8f0;
                border-radius: 8px; padding: 4px;
            }
            QMenu::item {
                padding: 8px 24px; font-size: 13px; border-radius: 4px;
            }
            QMenu::item:selected { background: #eff6ff; color: #1e293b; }
            QMenu::separator {
                height: 1px; background: #e2e8f0; margin: 4px 8px;
            }
        """)

        view_action = menu.addAction("📋 View Details")
        view_action.triggered.connect(
            lambda: self._show_dossier_details(self.table.currentRow())
        )

        menu.addSeparator()

        copy_action = menu.addAction("📋 Copy Dossier Number")
        copy_action.triggered.connect(self._copy_dossier_number)

        copy_path_action = menu.addAction("📁 Copy File Path")
        copy_path_action.triggered.connect(self._copy_file_path)

        open_folder_action = menu.addAction("📂 Open Containing Folder")
        open_folder_action.triggered.connect(self._open_containing_folder)

        menu.addSeparator()

        delete_action = menu.addAction("🗑 Delete Selected")
        delete_action.triggered.connect(self.delete_selected)

        menu.addSeparator()

        export_action = menu.addAction("📥 Export All to CSV")
        export_action.triggered.connect(self.export_csv)

        menu.exec(self.table.viewport().mapToGlobal(position))

    def _copy_dossier_number(self):
        row = self.table.currentRow()
        if row >= 0:
            item = self.table.item(row, 1)
            if item:
                QApplication.clipboard().setText(item.text())
                self._set_status(f"Copied: {item.text()}")

    def _copy_file_path(self):
        row = self.table.currentRow()
        if row >= 0:
            item = self.table.item(row, 7)
            if item:
                QApplication.clipboard().setText(item.text())
                self._set_status(f"Copied path: {item.text()}")

    def _open_containing_folder(self):
        row = self.table.currentRow()
        if row < 0:
            return
        item = self.table.item(row, 7)
        if item and item.text():
            folder_path = os.path.dirname(item.text())
            if os.path.exists(folder_path):
                if os.name == 'nt':
                    os.startfile(folder_path)
                else:
                    os.system(f'xdg-open "{folder_path}"')
            else:
                QMessageBox.warning(
                    self, "Folder Not Found",
                    f"The folder does not exist:\n{folder_path}"
                )

    def _update_selection_count(self, *_args):
        count = len(self.table.selectionModel().selectedRows())
        self.lbl_selected_count.setText(f"Selected: {count}")

    def _set_status(self, message: str):
        self.lbl_status_info.setText(message)

    # ── CLEANUP ──────────────────────────────────────────────
    def closeEvent(self, event):
        """Ensure the generator thread is stopped before closing."""
        if self._generator_thread is not None:
            try:
                if self._generator_thread.isRunning():
                    self._generator_thread.requestInterruption()
                    self._generator_thread.wait(2000)
                self._generator_thread.deleteLater()
            except Exception:
                pass
            self._generator_thread = None
        super().closeEvent(event)